### ISSUE TITLE
duplicate interface definition for class 'RCTEventEmitter'

### ISSUE THREAD

**Issue by jinaddavid** [RevenueCat/react-native-purchases#160] opened 2020-07-27 11:40 UTC
Environment
    1. React Native 
        OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 153.21 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 

 

. Steps to reproduce, with a description of expected vs. actual behavior
1. yarn add react-native-purchases
2. react-native link react-native-purchases
3. cd ios pod install
4. React-native run-ios 
 
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. 

<img width="567" alt="Screenshot 2020-07-27 at 1 30 54 PM" src="https://user-images.githubusercontent.com/23101970/88537800-80f6d100-d00e-11ea-9c70-fe9e0d0a5d60.png">

 definition of 'RCTEventEmitter' must be imported from module 'React.React.RCTEventEmitter' before it is required

**Comment by aboedo** [comment] 2020-12-23 16:48
@jinaddavid whoa I'm not sure how we missed this issue, but I apologize for not replying. I believe this isn't reproducible with the latest version of the SDK, so I'm tentatively closing it, but feel free to reopen if it's still happening and we'll dig deeper.

**Closed by aboedo** 2020-12-23 16:48 UTC
Labels: bug

**Comment by kbrabrand** [comment] 2021-12-21 14:51
I'm experiencing the same issue with the latest Expo and `react-native-purchases` version (although my desired version is `4.1.0` – I'm in the middle of a expo upgrade process).

I figured that it was a problem in my xcode/RN/expo setup, but have reproduced the issue in a minimal repo with no other deps than expo, RN, react and `react-native-purchases`. Below are my dependencies as well as a video showing the whole process including

1. creation of a new expo project
2. building and running in an emulator after initializing
3. adding `react-native-purchases`
4. the build failing due to `duplicate interface definition`

**My package.json** 👇 
```
{
  "name": "purchases-expo-issue",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~44.0.0",
    "expo-splash-screen": "~0.14.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-purchases": "4.1",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

**A gist showing the console output of the process**
https://gist.github.com/kbrabrand/585cb289fdaaec9c07f412e1188122ec

**A tarball of the repo at the point of the error (excluding the node_modules and ios/Pods folders)**
https://www.dropbox.com/s/0vjuz7vvjjggybs/purchases-expo-issue.tar.gz?dl=0

**Comment by TrustyTechSG** [comment] 2021-12-22 04:22
Im also facing this issue on newest ExpoSDK44

**Comment by kbrabrand** [comment] 2021-12-24 12:36
I've researched a bit more, and the issue seems to be with expo modules and RNPurchases. Since universal modules is deprecated and Expo modules are taking over this affects close to all projects in the the RN landscape (given that the default when starting new React Native projects is to start it with expo...).

@aboedo

**Comment by benmajor** [comment] 2021-12-28 22:25
I can also confirm that I'm having the same issues with Expo SDK 44.

**Comment by kbrabrand** [comment] 2021-12-28 22:30
@benmajor A fix for this has been merged by the RC team, and will probably be released soon :) For the time being you can, as a workaround, install the `75e3c5a99430168fac3a2a28c17238408580fcb3` commit of the main branch directly through npm. It contains the fix that was merged.

**Comment by benmajor** [comment] 2021-12-29 16:41
Thanks @kbrabrand - I can confirm installing that commit worked a charm. For future reference, here's how you can install the specific commit into your project:

```
npm install --save "git://github.com/RevenueCat/react-native-purchases.git#75e3c5a99430168fac3a2a28c17238408580fcb3"

**Comment by benmajor** [comment] 2021-12-30 07:34
As a postscript to my post below, it's worth noting that when installing packages via the `git:` protocol, the build will fail in EAS with an `npm` issue. I suspect it's because the Expo build servers don't support Git OOB. As such, I updated the the requirement inside of `packages.json` to use HTTPS instead.

It may be worth running the following instead:

```
npm install --save "https://github.com/RevenueCat/react-native-purchases.git#75e3c5a99430168fac3a2a28c17238408580fcb3"
```

**Comment by aboedo** [comment] 2022-01-03 13:51
Update here: version 4.5.1 has been released with the fix, give it a try! Thanks everyone for reporting.
