### ISSUE TITLE
Cannot install on React Native 0.60+

### ISSUE THREAD

**Issue by felixchan** [RevenueCat/react-native-purchases#83] opened 2019-09-17 07:12 UTC
I love this, but have trouble installing.

`yarn add react-native-purchases`
`react-native link react-native-purchases` (What about auto-linking?)

I now see `pod 'RNPurchases', :path => '../node_modules/react-native-purchases'` inside my Podfile.

`cd ./ios; pod install`

I get:

```
[!] CocoaPods could not find compatible versions for pod "Purchases":
  In Podfile:
    RNPurchases (from `../node_modules/react-native-purchases`) was resolved to 2.4.1, which depends on
      Purchases (~> 2.6.0)

None of your spec sources contain a spec satisfying the dependency: `Purchases (~> 2.6.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by felixchan** [comment] 2019-09-17 07:14
Note: do I need to enable ` In-App Purchase` in Target/Capabilities? (Don't see it anywhere in the React Native quickstart doc page, but I see it on iOS install page)

**Comment by vegaro** [comment] 2019-09-17 16:28
Duplicate of this https://github.com/RevenueCat/react-native-purchases/issues/80

Regarding the Target/Capabilities, yes, you should enable it. I will add it to the quickstart doc page.

**Closed** 2019-10-31 20:46 UTC
