### ISSUE TITLE
tvOS projects based on expo cannot install react-native-purchases

### ISSUE THREAD

**Issue by wengqianshan** [RevenueCat/react-native-purchases#947] opened 2024-03-15 18:04 UTC
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform:tvOS
   2. SDK version: 7.24.0
   3. OS version: 17.4
   4. Xcode/Android Studio version: Xcode 15.3
   5. React Native version:  react-native-tvos@0.73.6-0
   6. SDK installation (CocoaPods + version or manual): expo
   7. How widespread is the issue. Percentage of devices affected.  Must appear
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior

a. Create a tvOS project
https://github.com/expo/examples/tree/master/with-tv

b. Install `react-native-purchases`
```
npx expo install react-native-purchases
```

An error occurs at this time:
```
$ npx expo install react-native-purchases
› Installing 1 other package using npm
> npm install --save react-native-purchases
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: wktv@2.0.0
npm ERR! Found: react-native@0.73.6-0
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-tvos/virtualized-lists@0.73.6-0
npm ERR!   node_modules/@react-native-tvos/virtualized-lists
npm ERR!     @react-native-tvos/virtualized-lists@"0.73.6-0" from react-native@0.73.6-0
npm ERR!   react-native@"npm:react-native-tvos@^0.73.6-0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! react-native-purchases@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-native@0.73.6
npm ERR! node_modules/react-native
npm ERR!   peer react-native@">= 0.58.2" from react-native-purchases@7.24.0
npm ERR!   node_modules/react-native-purchases
npm ERR!     react-native-purchases@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
...
```

c. Force installation
```
npx expo install react-native-purchases -- --force
```

Report an error again
```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes
```

At this time, the native module of `react-native-purchases` cannot be found in the `ios/Podfile.lock` file

d. Try to use `yarn install`, but the error in step c is still displayed.

6. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

Also try to install `react-native-iap` in the same way, it can run normally, and you can find something similar to the following in the ios/Podfile.lock file

```
RNIap:
  :path: "../node_modules/react-native-iap"
```

**Comment by GiomScript** [comment] 2024-03-18 15:36
I have the same exact problem.

**Comment by mshmoustafa** [comment] 2024-03-19 22:04
Hey all,
I've pinged the mobile engineering team for assistance, I'll update this issue with their input.

**Comment by vegaro** [comment] 2024-03-21 13:27
Can you please share your dependencies in your package.json so we can try to replicate? Thanks!

**Comment by wengqianshan** [comment] 2024-03-21 13:40
ok, just like this

```json
{
  "name": "wktv",
  "version": "2.0.0",
  "dependencies": {
    "expo": "^50.0.11",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "npm:react-native-tvos@^0.73.6-0",
    "react-native-purchases": "^7.24.0"
  },
  "devDependencies": {
    "@babel/core": "~7.20.0",
    "@react-native-tvos/config-tv": "^0.0.7",
    "@types/react": "~18.2.45",
    "typescript": "^5.3.0"
  },
  "expo": {
    "install": {
      "exclude": [
        "react-native"
      ]
    }
  },
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  }
}
```

you can follow this step to create a test project: https://github.com/expo/examples/tree/master/with-tv

**Comment by wengqianshan** [comment] 2024-03-21 16:40
<img width="1913" alt="image" src="https://github.com/RevenueCat/react-native-purchases/assets/854370/b3baf35d-34f2-4825-a7f3-feb40b06812c">

By comparing the .podspec file, I found that the `react-native-iap` module `s.platforms` contains `tvos`, but `react-native-purchases` does not. (`react-native-iap` worked fine for expo tvOS project)

**Comment by vegaro** [comment] 2024-03-21 19:51
I've been trying to work this out but I am struggling with Expo, I am able to install the dependency if using this branch I just created that adds the tvos platform and changes the react native dependencies to `*`

```
    "react-native-purchases": "RevenueCat/react-native-purchases#tvos"
```

```
  "peerDependencies": {
    "react": "*",
    "react-native": "*"
  },
```

Do you mind giving that a try? If that branch works, we can make a release with the fix.

Thank you!

**Comment by wengqianshan** [comment] 2024-03-22 04:08
@vegaro 
Thank you very much. I can install the module after trying it, but I get an error when using it. Invariant Violation: 

```
ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes
```

After `pod install`, I still can’t find the native module related to react-native-purchases in the `ios/Podfile.lock` file

**Comment by vegaro** [comment] 2024-03-22 07:50
Yes, I can reproduce... You're also getting the npm error when installing `react-native-iap` right? So you have to force install it, correct? But then it is correctly linking the pod

**Comment by wengqianshan** [comment] 2024-03-22 09:22
@vegaro yes that's it😄

**Comment by wengqianshan** [comment] 2024-03-22 09:27
Later I tried to modify react-native-purchases :
```
s.platforms = { :ios => "10.0" , :tvos => "10.0"}
```

The pod was magically installed, but the following error occurred

<img width="1346" alt="截屏2024-03-22 00 57 41" src="https://github.com/RevenueCat/react-native-purchases/assets/854370/9f7f58e3-2266-45eb-8194-9759e7cb34ee">

**Comment by vegaro** [comment] 2024-03-22 09:33
Oh that's interesting. You modified it in the node modules folder? I was doing that this morning but it wasn't installing either. Looks like you dropped the platform to 10 though?

**Comment by wengqianshan** [comment] 2024-03-22 09:48
@vegaro 
Yes, I modified it in node_modules with the help of [patch-package](https://github.com/ds300/patch-package).

It doesn't work for you may be you are using a `platform` instead of `platforms`.

**Comment by vegaro** [comment] 2024-03-22 10:45
you were right @wengqianshan , I was doing `platform` instead of `platforms`...

I pushed again to that tvos branch some conditional checks that prevent the compilation issues. It looks like the SDK is getting configured when I run it.

Can you test it works on your end? If it does, we can maybe throw a release next week adding support for this.

Thanks!

**Comment by wengqianshan** [comment] 2024-03-22 12:42
@vegaro 
It works fine, thank you so much！
<img width="1235" alt="image" src="https://github.com/RevenueCat/react-native-purchases/assets/854370/c4462f62-0623-49a0-8c0e-34f092a70a20">

**Comment by vegaro** [comment] 2024-03-27 14:50
Amazing, I will try to get that merged soon 😄

**Closed** 2024-04-05 14:11 UTC
Labels: bug

**Comment by wengqianshan** [comment] 2024-04-06 04:22
Thank you! I have installed version 7.26.0 and it runs perfectly. It's amazing!
