### ISSUE TITLE
After update package 4.1.2 - crash issue in Restoring transactions 

### ISSUE THREAD

**Issue by KPUbhada** [RevenueCat/react-native-purchases#248] opened 2021-05-26 03:26 UTC
- SDK - 4.1.2
- After update package app crash on Purchases.syncPurchases on iOS.

**Sandbox testing app crash on **Purchases.syncPurchases** method**
WARN: 🍎‼️ App running in sandbox without a receipt file. Restoring transactions won't work until a purchase is made to generate a receipt. This should not happen in production unless user is logged out of Apple account.
ERROR: 🍎‼️ The receipt is missing.

Previous version 4.1.1 not reported crash when check Purchases.syncPurchases method. May be this version not handle this crash issue.

**Comment by aboedo** [comment] 2021-05-26 15:08
hi! 👋 Thanks for reporting!

Could you share the actual crash or stack trace so we can investigate? The debug logs help might not be enough here, since they don't mention the actual exception.

**Comment by KPUbhada** [comment] 2021-05-27 04:20
Step to reproduce issue

=> I have call synch method when user open app first time. - User no any subscription right now in his device and call this method. I have only test sandbox account(I have not test with production account)
=> Method = **const purchaserInfo = await Purchases.syncPurchases();**
=> App crash and show log for crash because of no any previous transition found. If user already purchase any subscription then no any crash because restore successfully.

=> Previous version of app no facing any crash issue but after update new version facing crash when call .syncPurchases() method in sandbox account.
=> Now I have again decrease version because of crash.

If you generate this issue. Just follow this step
1. When start app directly call syncPurchases() method. Defiantly your app goes crash.
2. User this - const purchaserInfo = await Purchases.syncPurchases();

Thanks
Ketan

**Comment by rkotzy** [comment] 2021-05-27 14:57
Is there a crash log or stack trace? We can't reproduce on our side.

The debug logs you shared (below) are informational they shouldn't crash your app. Maybe there was some confusion there? 

> WARN: 🍎‼️ App running in sandbox without a receipt file. Restoring transactions won't work until a purchase is made to generate a receipt. This should not happen in production unless user is logged out of Apple account.
> ERROR: 🍎‼️ The receipt is missing.

**Comment by aboedo** [comment] 2021-05-27 16:32
@KPUbhada `syncPurchases` actually doesn't have a return, it's void, and it's not declared as async:
https://github.com/RevenueCat/react-native-purchases/blob/develop/src/purchases.ts#L457

Calling `const purchaserInfo = await Purchases.syncPurchases();` wouldn't give you a result, unfortunately. 

That said, there's a crash in `syncPurchases` on iOS, I was able to reproduce. I'll work on a fix. Thanks again for posting!

**Comment by aboedo** [comment] 2021-05-27 16:44
Also, note that `syncPurchases` is not needed for most cases, only for very specific stuff. 
https://docs.revenuecat.com/docs/purchaserinfo

**Comment by KPUbhada** [comment] 2021-05-28 04:36
@aboedo 
I haven't call Purchases.syncPurchases() method every time. I have follow document. This only call if update app normal subscription to move to RevenueCat subscription app version.

**Comment by aboedo** [comment] 2021-06-09 13:53
@KPUbhada release 4.1.3 is out now with the fix! Thanks again for reporting! I'm closing this issue now, but let us know if you run into any more issues!

**Closed by aboedo** 2021-06-09 13:53 UTC
Labels: bug, status: needs-additional-info
