### ISSUE TITLE
Could not build Objective-C module 'PurchasesHybridCommon'

### ISSUE THREAD

**Issue by walterholohan** [RevenueCat/react-native-purchases#342] opened 2022-03-17 15:21 UTC
Hi,

The following issue (https://github.com/RevenueCat/react-native-purchases/issues/200) was closed but I am still experiencing the error when I do a release build of a new scheme (i.e. staging, prod etc) of my React Native app. This was fine until now as we had a workaround of removing the `build` and `pods` folders and reinstalling the pods i.e. `rm -rf ios/build && rm -rf ios/pods && yarn && cd ios && pod install` every time we switched schemes and wanted to do a new release build.

However, in the last few days, we have added an Apple Watch Extension to our RN app which is built using SwiftUI. Anytime that we try to build the Watch App with preview mode enabled (https://developer.apple.com/documentation/swiftui/previews-in-xcode) it fails with the following errors.

```
 Declaration of 'RCPurchases' must be imported from module 'Purchases' before it is required
```

```
Could not build Objective-C module 'PurchasesHybridCommon'
```

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/5293650/158833720-95f469ed-9c85-4fc5-be16-11254a25839e.png">

Is there any workaround to this? It is not feasible for us to rebuild the native watch app every time we make changes to the SwiftUI code. 

From reading through https://github.com/RevenueCat/react-native-purchases/issues/200 it seems that no fix was ever replaced. Any help would be greatly appreciated, as we want to release our Apple Watch app to our users in the next couple of weeks.

Thanks,
Walter

**Comment by aboedo** [comment] 2022-03-18 18:01
@walterholohan 🤔 
A couple of questions: 

- Which RN version are you using? 
- Which Cocoapods version are you using? 
- Which react-native-purchases version are you using? 

The fact that you have to remove the pods every time and re-add them makes me think that there's something messing up the pods setup. In a react-native project, react-native does a lot of code generation for the project, that might be conflicting with the actual pod itself. 

Could you let us know about the versions you're using so we can try to reproduce this on our end?

**Comment by walterholohan** [comment] 2022-03-20 21:54
Hi @aboedo , thanks for the reply. Answers to questions below 👇 

- Which RN version are you using? `0.66.4`
- Which Cocoapods version are you using? 
```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.2.1 (21D62)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```
- Which react-native-purchases version are you using? `4.5.2`

**Comment by aboedo** [comment] 2022-03-21 19:17
🤔 I hadn't noticed that this started with the apple watch app...

Maybe the watchOS app doesn't have the SDK installed? 

I'm going to try adding a watchOS app to my test app to see if I get to reproduce

**Comment by walterholohan** [comment] 2022-03-22 10:41
Thanks @aboedo below are the steps that I am doing to reproduce the issue when running an apple watch extension with our RN app in xCode:

1. Start metro bundler
2. Press cmd + k to clean build folder in Xcode
3. Press `Run` button on `WatchApp` target
4. Wait for build to finish
5. Opened a swiftUI view in the WatchApp directory in Xcode
6. Pressed Resume in Canvas
7. Waited for `Build for Preview` to finish
8. `Build for preview` fails

Here is the snapshot of the xCode build errors:
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/5293650/159463866-2e52ea80-82fa-4f80-ac6d-8efd2a783e2d.png">

**Comment by aboedo** [comment] 2022-03-22 22:13
@walterholohan 🤔 
It looks like the watch app is trying to compile the Purchases plugin, but doesn't actually have it linked as a Pod. 

A couple of questions: 
- are you using the SDK from the watch app? 
- if so, how are you linking the watch app and the SDK? Perhaps there's something missing for it to link the plugin correctly.
- if not, we should try to investigate why the watch app is trying to compile the plugin. Maybe there's a class in the watch app target that references a type in the plugin?

Would you be able to share the Podfile in case we can actually spot something in it?

**Comment by walterholohan** [comment] 2022-03-23 10:02
@aboedo 

Our watch app is just an extension to our RN app, so I presume it is compiling the SDK as it's building the mobile app along with the watch app at the same time. Our `podfile` is below, but as you can see it's just the default RN `podfile`. The strangest thing is that it will build successfully the first time round but when we try to `build for preview` (used to develop SwiftUI views in Canvas on Xcode) it will fail with the above.

If I remove `react-native-purchases` from our project then `build for preview` completes successfully which would indicate that something funky is happening with the pod installation in the SDK.

The issue isn't only just isolated to the Apple Watch build. I can also reproduce it every time I switch between two targets and try to do a `Release` build. Steps below:

1. Build `Target1` in release mode
2. `Target1` will build successful
3. Try build `Target2` in release mode
4. `Target2` build will fail (error below)

I am happy to jump on a Zoom call with you and we can try to debug it on our project, if that will make things easier for you?

Build error:
```
❌  /Users/walterholohan/Projects/rb-app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchases+HybridAdditions.h:12:12: declaration of 'RCPurchases' must be imported from module 'Purchases' before it is required
```

Podfile:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'RunBuddyApp' do
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'RunBuddyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

**Comment by aboedo** [comment] 2022-03-24 21:07
@walterholohan happy to jump on a zoom call to figure this one out. I have some availability tomorrow. There's contact information in my [GH profile](https://github.com/aboedo) that we can use to figure out scheduling

**Comment by walterholohan** [comment] 2022-03-24 21:41
@aboedo I was only able to see your twitter page on your GH profile, but I am not on twitter so I cant message you via that channel. My email is walter@therunbuddy.co.uk if you want to send me an email. I'm based in London so will be free all day tomorrow up until 6pm London time.

**Comment by aboedo** [comment] 2022-03-25 13:56
I sent you an email to figure out scheduling 👌

**Comment by aboedo** [comment] 2022-03-25 17:45
Update for anyone reading this: 
We were able to solve the issue by adding a single, empty Swift file to the project. 

@walterholohan let us know if you run into anything else! Thanks for reporting and have a great day!

**Comment by aboedo** [comment] 2022-03-28 19:21
@walterholohan I'm tentatively closing this ticket, feel free to reopen if you still experience issues!

**Closed by aboedo** 2022-03-28 19:21 UTC

**Comment by ZebraDigital** [comment] 2022-06-25 09:07
Hi, I am having the same issue. Building the Unity project with the RevenueCat SDK.

After building the Xcode project from Unity I built the project in the Xcode to test in SandBox environment. It was built successfully and it worked fine. Then I tried ti build it for the AppStore and the following error appeared:

<PurchasesHybridCommon/PurchasesHybridCommon.h> file not found

I cleared Xcode cache and Derived Data folder it didn't help. Then I reinstalled the Xcode and was able to build once again. Then I made some changes and now it doesn't build again with the same issue.

I updated and reinstalled the Xcode project and it doesn't help. Please help!)

**Comment by aboedo** [comment] 2022-06-25 11:18
@ZebraDigital the solution for the previous reporter was to add a single, empty Swift file to the project. This ensured that Swift support was enabled for the app. 

Give it a shot! Also, make sure that you're opening the `.xcworkspace` file and not the `.xcproj` file for your project.

**Comment by ZebraDigital** [comment] 2022-06-25 12:40
Sorry for bothering, could you please give more details? What should be the name of the Swift file and to what folder should add it? 

Thank you! 🙏

**Comment by ZebraDigital** [comment] 2022-06-25 14:00
<img width="1440" alt="Screen Shot 2022-06-25 at 19 58 59" src="https://user-images.githubusercontent.com/85200965/175776848-9fb180eb-8eaf-49e6-884e-479d7d2c1ef5.png">

Added the empty SwiftFile to the xcworkproject then tried to build from the .scproj 

Unortunately didn't work

**Comment by aboedo** [comment] 2022-06-27 19:33
@ZebraDigital here are a few things to try: 

- Update to the latest version of the SDK (for unity, that'd [be 3.5.3 available here](https://github.com/RevenueCat/purchases-unity/releases/tag/3.5.3)). 

> then tried to build from the .scproj

Just a small clarification: you need to open from the `.xcworkspace` file and *not* the `.xcproj` file 

- On the navigation pane on the left, select Unity-iPhone, then on Targets, UnityFramework, and then in build settings select *Always Embed Swift Standard Libraries* and update the value to YES. Also in build settings, ensure the value of Swift Language Version is set to 5. Lastly, ensure that the iOS deployment target is set to iOS 9 or higher. 
- Ensure that the value of the [swift version isn't overridden by the Podfile](https://github.com/RevenueCat/purchases-flutter/issues/168#issuecomment-796468415).
- `cd` into the iOS project folder and run `pod install`, then try building again. 

Hope this helps!

**Comment by ZebraDigital** [comment] 2022-06-30 13:30
Oh, that was the problem!

"you need to open from the .xcworkspace file and not the .xcproj file"

Not obvious but crucial. Now it works! Thank you @aboedo

**Comment by aboedo** [comment] 2022-06-30 14:09
Glad it's working! And thanks for reporting back. 
Have a great day!

**Comment by Sydney-o9** [comment] 2023-06-25 11:32
I had to do:
```bash
pod deintegrate
pod install
```
