### ISSUE TITLE
Wrong typescript typings for `PurchasesIntroPrice`

### ISSUE THREAD

**Issue by xseignard** [RevenueCat/react-native-purchases#331] opened 2022-02-14 08:58 UTC
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Platform: Android
   2. SDK version: 4.5.2
   3. OS version: 12
   4. Xcode/Android Studio version: not relevant
   5. React Native version: 0.67.2
   6. SDK installation (CocoaPods + version or manual): not relevant
   7. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior

- purchase a subscription with an intro price and note that [`PurchasesIntroPrice`](https://github.com/RevenueCat/react-native-purchases/blob/main/src/offerings.ts#L168-L193) properties are not `null` 
- after a few time cancel it
- purchase again and note that [`PurchasesIntroPrice`](https://github.com/RevenueCat/react-native-purchases/blob/main/src/offerings.ts#L168-L193) properties are `null` 

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

The above situation is expected, it is only the `PurchasesIntroPrice` that should be fixed with something like:
```ts
export interface PurchasesIntroPrice {
    /**
     * Price in the local currency.
     */
    readonly price: number | null;
    /**
     * Formatted price, including its currency sign, such as €3.99.
     */
    readonly priceString: string | null;
    /**
     * Number of subscription billing periods for which the user will be given the discount, such as 3.
     */
    readonly cycles: number | null;
    /**
     * Billing period of the discount, specified in ISO 8601 format.
     */
    readonly period: string | null;
    /**
     * Unit for the billing period of the discount, can be DAY, WEEK, MONTH or YEAR.
     */
    readonly periodUnit: string | null;
    /**
     * Number of units for the billing period of the discount.
     */
    readonly periodNumberOfUnits: number | null;
}
```

don't you think?

**Additional context**

Here is a screenshot of what I have in my app.
![Screenshot_20220214-092821](https://user-images.githubusercontent.com/515603/153832172-f708732e-08ac-4e79-a09a-03b25cfc89d4.png)

**Comment by beylmk** [comment] 2022-02-14 22:29
Hey @xseignard, thanks for bringing this to our attention! You're definitely right, these should be marked nullable if they can come back as null. Will update here once fixed!

**Comment by vegaro** [comment] 2022-02-14 22:46
I think ideally, `introPrice` itself would be nullable instead. I don't think we intend the properties to be nullable. I am not sure how that happened

**Comment by beylmk** [comment] 2022-02-14 23:19
Going to confirm behavior in a sample app. Perhaps we have a bug in our hybrid-native middle layer, purchases-hybrid-common...

**Comment by xseignard** [comment] 2022-02-16 15:56
Hi there, thanks for your reactivity 🤗 
@vegaro I can see that `introPrice` is itself [nullable](https://github.com/RevenueCat/react-native-purchases/blob/main/src/offerings.ts#L130), and I was expecting to receive `null` for it instead of an object full of `null` properties. So as @beylmk says, there may be some bug creating the `introPrice` object instead of make it `null`

**Comment by joshdholtz** [comment] 2022-02-22 13:24
@xseignard Hey! I've been working on trying to reproduce this and I'm not having any luck 😔 I'm trying with SDK `4.5.2`, on Android 12. I'm either getting:
- `"introPrice": {"cycles": 2, "period": "P1W", "periodNumberOfUnits": 7, "periodUnit": "DAY", "price": 0.99, "priceString": "$0.99"}`
- `introPrice: null`

## Out Loud Thinking
`introPrice` (or it's other related fields) should also never turn `null` even after subscribing and cancelling 🤔 . It should only ever be `null` if there isn't any defined intro price for you IAP in Google Play. (At least, this is what the behavior should be)

This pull request (https://github.com/RevenueCat/purchases-hybrid-common/pull/106) should have also prevented the `introPrice` from being a map/object of keys with null values. 

## Idea
It _almost_ seems like this might be some reference or memory issue where the values in the `introPrice` object are turning to `null`. I have no real reason to back that up though or know how that's possible 😓

## Follow Up Questions
1. Is this only happening where you subscribe and cancel in the same app session? If you kill/force close the app and restart the app after cancelling, does everything run as expected or do you still get this error?
2. Which call are you getting `"introPrice": {"cycles": null, "period": null, "periodNumberOfUnits": null, "periodUnit": null, "price": null, "priceString": null}` from? Is it `getOfferings` or `getProducts` (or something else)?
3. What is your subscription and intro setup? Is your intro free, single, or recurring? Just want to make sure we are testing the exact same way you are 🤞 

Thanks for reading through my thoughts and questions! Hoping we can figure out what's going for you soon ☺️

**Comment by jamesisaac** [comment] 2022-03-07 13:55
@joshdholtz We ran into this issue in the following way:

- Create an In-App Subscription on Google Play with an Introductory Price (yearly subscription with first year at reduced price).
- Confirm this comes through correctly via RC's `Purchases.getOfferings()` call.
- Remove the Introductory Price.
- RC now returns a payload which breaks its TypeScript contract: `"introPrice": {"cycles": null, "period": null, "periodNumberOfUnits": null, "periodUnit": null, "price": null, "priceString": null}`

For us this then resulted in a runtime error (`null is not an object`) impacting all Android users who visited our pricing page, because we were checking for existence on `introPrice` as the types show, not the individual fields.

Ideal would be if `introPrice` could return null, but if not I think the typedefs should be updated as a priority... quite unexpected to have a settings change in Google Play Console lead to a runtime error from a condition which the types rule as impossible.

**Comment by vegaro** [comment] 2022-03-18 22:55
@jamesisaac I was looking into this, and tried to reproduce if following your instructions, and I wasn't able to get your result. In any case, looking at the code of `purchases-hybrid-common` version 2.0.1 (the one `react-native-purchases` 4.5.2 uses) there is no way this could be returned.

We fixed this exact same bug in https://github.com/RevenueCat/purchases-hybrid-common/pull/106, which was released in purchases-hybrid-common 1.11.2. react-native-purchases < 4.5.2 would have the bug and see what you are seeing for cases where intro price is null. 

Is is maybe possible you are actually not testing with 4.5.2 code? Do you mind sharing the output of running `./gradlew androidDependencies` inside the `android` folder of the React Native project where you are able to reproduce it?

Thanks! And sorry we haven't found a solution yet.

**Comment by jamesisaac** [comment] 2022-03-18 23:41
@vegaro That is likely it, as our project was on 4.5.1!  Apologies, missed the point that a fix for this was meant to have just landed in 4.5.2.  I think before replying here I did check the 4.5.2 release notes and the changelogs linked for the other packages, and saw nothing relevant, but now I see that `purchases-hybrid-common` had multiple releases since 4.5.1.  Thanks for clearing that up.

**Comment by vegaro** [comment] 2022-03-21 20:48
Amazing! Mystery solved 😄 

I will close this issue then. Thanks for opening anyway!

**Closed by vegaro** 2022-03-21 20:48 UTC
Labels: bug

**Comment by jamesisaac** [comment] 2022-03-21 23:48
Just to clarify, I have no affiliation with @xseignard who originally opened this issue and does claim to be on 4.5.2 -- might be that they have a different scenario where this still can occur even with the latest fixes.

**Comment by vegaro** [comment] 2022-03-22 00:03
Thanks for clarifying! I had understood that you were working in the same project. In any case, let's see if @xseignard can say something about their project.
