### ISSUE TITLE
getEntitlements() is slow. Add caching?

### ISSUE THREAD

**Issue by KevinColemanInc** [RevenueCat/react-native-purchases#43] opened 2019-01-28 09:11 UTC
Between Apple and RevenueCat's API, I found just calling `setup` and `getEntitlements` is slow (like 6-7s.)

My quick fix was to fetch that information every time the app loads and then cache it to disk so I can quickly show the pricing information to the user.

It would be great if the package could do the caching for us instead of needing to do it ourselves.

**Comment by vegaro** [comment] 2019-01-28 21:17
We currently have caching for entitlements in place. The problem is that the setup call promise completes before the setup API calls have completed (and therefore before the caches are set). The new version of the SDK will fix a bunch of problems regarding this, so I will close this for now.

**Closed by vegaro** 2019-01-28 21:17 UTC
