### ISSUE TITLE
[Android] There is no singleton instance

### ISSUE THREAD

**Issue by dpyeates** [RevenueCat/react-native-purchases#101] opened 2019-12-23 16:26 UTC
Library version: 3.0.4

Upon installation and build on Android, when running the application I immediately get a no singleton instance. 

Looking at the logcat I get the following further info:

`
2019-12-23 16:20:30.576 12271-12412/com.sensorworks.fdeck E/unknown:ReactNative: Exception in native call
    kotlin.UninitializedPropertyAccessException: There is no singleton instance. Make sure you configure Purchases before trying to get the default instance.
        at com.revenuecat.purchases.Purchases$Companion.getSharedInstance(Purchases.kt:969)
        at com.revenuecat.purchases.common.CommonKt.getPurchaserInfo(common.kt:240)
        at com.reactlibrary.RNPurchasesModule.getPurchaserInfo(RNPurchasesModule.java:172)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by vegaro** [comment] 2019-12-23 18:11
Where are you calling `Purchases.setup`?

**Comment by dpyeates** [comment] 2019-12-24 15:20
I am using React native with mobx-state-tree and I am calling setup in a store afterCreate method.

The same store/app/purchases call works OK on IOS, but on Android I get the above error.

**Comment by dpyeates** [comment] 2019-12-31 10:57
Have upgraded to version 3.0.6 but still having the same issue. Works fine on IOS.

<img width="549" alt="Screenshot 2019-12-31 at 10 54 51" src="https://user-images.githubusercontent.com/944670/71619411-2dc5b880-2bbc-11ea-8c09-4e487e13468f.png">

**Comment by vegaro** [comment] 2020-01-02 10:07
You're calling setup in a store afterCreate method, but when are you calling `getPurchaserInfo`? 

What's happening here is that `getPurchaserInfo` gets called before the shared instance is set by the setup call

**Comment by KDederichs** [comment] 2020-01-02 14:27
@vegaro I have the same issue, though I'm not calling `getPurchaserInfo` at all, seems to be related to passing a user ID on initialisation. (`Purchases.setup(REVENUECAT_API_KEY, USER_ID)`)
If you remove the user ID it will still fail but with `getOfferings` as method that's causing the exception. (At least in my case)

**Comment by dpyeates** [comment] 2020-01-02 14:30
I have managed to get it working after moving my Purchases.setup and getProducts call to after my splash screen is shown. I think maybe that for some reason the initialisation of the Purchases Singleton seems to be taking a long time on Android?

**Comment by KDederichs** [comment] 2020-01-06 13:03
It still shouldn't do that though, especially since it works in 3.0.2

**Comment by vegaro** [comment] 2020-01-07 17:14
The issue here is a race condition when getProducts/getOfferings or any other function gets hit before the setup finishes setting up (before the instance is set) which is easy to reproduce if the setup is called in a different thread than the other functions. Do you know if setup and getProducts/getOfferings are being called in the same thread?

**Comment by KDederichs** [comment] 2020-01-13 16:58
@vegaro In my case it's literally just the `Purchases.setup(REVENUECAT_API_KEY, USER_ID)`.
The actual `getOfferings` is in a modal that isn't shown till requested by the user.

**Comment by i6mi6** [comment] 2020-04-10 15:47
This happened when I called `Purchases.reset()` without calling `Purchases.setup(...)`

**Comment by yaronlevi** [comment] 2020-04-27 13:55
Hi (-:
This is still an issue.

react-native-purchases@3.1.0
react-native@0.61.5

We learned about the issue because of the automatic e2e tester of the Google Play Store.
The tester just randomly taps some buttons on the first screen, so the test didn't even reach and code that calls Purchase.setup() or any other call to react-native-purchases.

This is the logcat error:
```FATAL EXCEPTION: mqt_native_modules
Process: com.rumble_mobile, PID: 18250
kotlin.UninitializedPropertyAccessException: There is no singleton instance. Make sure you configure Purchases before trying to get the default instance.
	at com.revenuecat.purchases.Purchases$Companion.getSharedInstance(Purchases.kt:1202)
	at com.revenuecat.purchases.common.CommonKt.getPurchaserInfo(common.kt:240)
	at com.revenuecat.purchases.react.RNPurchasesModule.getPurchaserInfo(RNPurchasesModule.java:174)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:193)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:764)
```

Also, this, if it helps, this is a video recording of the e2e:

![aaa](https://user-images.githubusercontent.com/5398977/80380078-b709a500-88a7-11ea-9c3a-c9ea699f5282.gif)

**Comment by IceDev-xyz** [comment] 2020-06-01 01:53
For anyone still having this issue, I fixed it by calling Purchases.setup in the constructor.

**Comment by vegaro** [comment] 2020-06-03 15:55
Closing this since it's not a bug in the SDK. This occurs when calling a function that requires an instance (like `getOfferings`, or `getPurchaserInfo`) before calling `Purchases.setup`.

`Purchases.setup` should be called as soon as possible, preferably when the app is initialized. The setup call will make sure the caches are up to date, so it's not necessary to call `getOfferings` or `getPurchaserInfo` when the app is initialized, and they should be called only when it's necessary.

**Comment by dpyeates** [comment] 2020-06-14 20:13
Just to say I am still seeing this in production on a very small number of devices.

<img width="1251" alt="Screenshot 2020-06-14 at 21 10 56" src="https://user-images.githubusercontent.com/944670/84603118-d2466900-ae83-11ea-8e56-91358d27ab64.png">

**Comment by uareurapid** [comment] 2020-12-14 14:36
clearly a bug on your side, everybody is having the same issue, even with different sdks/platforms
common guys!!!!

**Comment by rkotzy** [comment] 2020-12-14 20:53
While this issue does gets reported frequently, we are unable to reproduce it in samples and don't have reason to believe it's a react native SDK bug. This crash occurs when a function that requires an instance (like `getOfferings`, or `getPurchaserInfo`) is triggered before calling `Purchases.setup`. The crash here is intentional so it can hopefully be caught during development, but maybe there's a more graceful way things can be handled.

Maybe these related issues can help:
- https://github.com/RevenueCat/purchases-android/issues/198
- https://github.com/RevenueCat/purchases-android/issues/83

**Comment by vegaro** [comment] 2021-10-29 22:13
I am not sure I understand your suggestion @tarouboy , could you please clarify? Thanks

**Comment by pcdreamssoftware** [comment] 2021-10-30 11:54
it think his point is actually very clear. If there was no need for the user call the `setup` from JS code, and instead this was done on the native side (whenever everything is already in place), it would not be error prone as it is right now.. Doesn´t make much sense that an app crashes just because someone calls a couple of methods on the wrong order or at the wrong time. Either this is hidden from the user action, or it must be protected in some way

**Comment by tarouboy** [comment] 2021-10-31 17:40
> I am not sure I understand your suggestion @tarouboy , could you please clarify? Thanks

Just like what @pcdreamssoftware said.

In my case, I couldn't catch the crash during development. Hence, on production it crashs randomly on some older devices.

Please don't crash the app intentionally even the `Purchases.setup` didn't execute. I prefer the user couldn't get the offerings rather than crashing.

My suggestion is fine-tuning the installation steps to make sure the flow is always correct if it's so important ( but not crashing it ). Like by pasting the `setup` code on the native side, so the `setup` will be executed before any other functions.

**Comment by vegaro** [comment] 2021-11-03 21:56
Thanks for clarifying, it would definitely be less error prone, but at the same time, introducing extra configuration steps makes it more points of failure, specially for devs not as familiar with native development, so we could be introducing other problems. Giving the flexibility is definitely something we are exploring though. I have a question for you @tarouboy and @pcdreamssoftware: How are you configuring the plugin? Are you doing it like in https://github.com/RevenueCat/react-native-purchases/blob/main/examples/MagicWeather/App.js#L20

**Comment by tarouboy** [comment] 2021-11-05 10:17
> Thanks for clarifying, it would definitely be less error prone, but at the same time, introducing extra configuration steps makes it more points of failure, specially for devs not as familiar with native development, so we could be introducing other problems. Giving the flexibility is definitely something we are exploring though. I have a question for you @tarouboy and @pcdreamssoftware: How are you configuring the plugin? Are you doing it like in https://github.com/RevenueCat/react-native-purchases/blob/main/examples/MagicWeather/App.js#L20
> 
> 
> 
> 

Yes. But I use React-native-navigation. I guess that's the reason.

**Comment by dpyeates** [comment] 2021-11-05 15:49
> > Thanks for clarifying, it would definitely be less error prone, but at the same time, introducing extra configuration steps makes it more points of failure, specially for devs not as familiar with native development, so we could be introducing other problems. Giving the flexibility is definitely something we are exploring though. I have a question for you @tarouboy and @pcdreamssoftware: How are you configuring the plugin? Are you doing it like in https://github.com/RevenueCat/react-native-purchases/blob/main/examples/MagicWeather/App.js#L20
> 
> Yes. But I use React-native-navigation. I guess that's the reason.

Same here. Maybe this is the common denominator?

**Comment by tarouboy** [comment] 2021-11-12 16:44
I am guessing it happens after the MainActivity being killed from the background.
So from now I will try to run the setup again see if the number of crashes will be reduced.

```
Navigation.events().registerAppLaunchedListener(() => {
      if (store) {
        //resume from background
        try{
          Purchases.setup('GuSTZJvGtlCXsBXdWsniXgXXaunKzqpg');
        }catch(error){
          console.log('ignore any error', error)
        }
        
        startApp();
      }
    });
```

**Comment by tarouboy** [comment] 2021-11-12 16:47
> Thanks for clarifying, it would definitely be less error prone, but at the same time, introducing extra configuration steps makes it more points of failure, specially for devs not as familiar with native development, so we could be introducing other problems. Giving the flexibility is definitely something we are exploring though. I have a question for you @tarouboy and @pcdreamssoftware: How are you configuring the plugin? Are you doing it like in https://github.com/RevenueCat/react-native-purchases/blob/main/examples/MagicWeather/App.js#L20

Is there any ways to check if the SharedInstance exists?

**Comment by tarouboy** [comment] 2021-11-15 02:54
Please reopen the issue. 
I am using the latest version and there're still a small amount of users experiencing this **kotlin.UninitializedPropertyAccessException**.

I guess if I haven't implement the setup code correctly, I guess the % of crashing will be much more?
So please stop thinking the developers didn't follow the implementation guide.

```
kotlin.UninitializedPropertyAccessException: 
  at com.revenuecat.purchases.Purchases$Companion.getSharedInstance (Purchases.kt:1760)
```

I have no experience with kotlin but I believe there's someway to check if the sharedInstance is still there before executing the code? Please try to catch this error and let the app crash.

**Comment by vegaro** [comment] 2021-11-17 01:42
@tarouboy Maybe it’s still possible that for some reason Navigation doesn’t trigger the registerAppLaunchedListener, setup wouldn't be called and therefore, calling logIn would trigger the exception.

Anyway, I’ve been looking into this because there’s clearly something strange if we are getting this many reports only for React Native and have realized that React Native is actually not propagating the exception to the JS layer and it just crashes, without giving you the possibility to do try/catch. Which is bad.

I think something we can do is, as you said, throw an error by rejecting the Promise. That way developers can do try/catch, otherwise there’s no way you can react if you get the exception. You could ignore it, you could call setup, show an error... And it will still notify developers if they actually have a race condition or have forgotten to call setup, which is the reason why we throw an error in Android first place.

**Comment by tarouboy** [comment] 2021-11-17 02:04
> @tarouboy Maybe it’s still possible that for some reason Navigation doesn’t trigger the registerAppLaunchedListener, setup wouldn't be called and therefore, calling logIn would trigger the exception.
> 
> Anyway, I’ve been looking into this because there’s clearly something strange if we are getting this many reports only for React Native and have realized that React Native is actually not propagating the exception to the JS layer and it just crashes, without giving you the possibility to do try/catch. Which is bad.
> 
> I think something we can do is, as you said, throw an error by rejecting the Promise. That way developers can do try/catch, otherwise there’s no way you can react if you get the exception. You could ignore it, you could call setup, show an error... And it will still notify developers if they actually have a race condition or have forgotten to call setup, which is the reason why we throw an error in Android first place.

Thank you. It will be perfect!

**Closed** 2021-12-06 21:36 UTC
Labels: triaged

**Comment by vegaro** [comment] 2021-12-08 16:18
Release [4.5.0](https://github.com/RevenueCat/react-native-purchases/releases/tag/4.5.0) has a bunch of fixes that should prevent this:

- Added `isConfigured`. Useful to be able check if the SDK is configured before those calls that are causing the exceptions.
- Accessing the instance before it's configured won't fire a Native exception anymore and it will be rejecting the promises with an `UninitializedPurchasesError`.

Please refer to the release's changelog for a more detailed version of the changes.

**Comment by ChrisCaninBLL** [comment] 2024-03-18 16:55
> Where are you calling `Purchases.setup`?

.setup is not offered on Purchases. Any other suggestions?
